name: AWS Lambda CICD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.LAMBDA_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.LAMBDA_SECRET_KEY }}
          aws-region: eu-north-1
      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name serverless --runtime 5min java17 --handler integration.ninjas.HandlerString::handleRequest --role arn:aws:iam::533267152024:role/lambda-perm --zip-file fileb://target/lambda-basic-1.0-SNAPSHOT.jar
        continue-on-error: true  
      - name: Update Lambda Function    
        run: aws lambda update-function-code --function-name serverless --zip-file fileb://target/lambda-basic-1.0-SNAPSHOT.jar
          
      
    
